---
# Built-in config:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

# We do not typically use/need class documentation
Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/RaiseArgs:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 6

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 3

Style/SingleLineMethods:
  Enabled: false

Rails:
  Enabled: true

# Run rails specific checks
AllCops:
  TargetRubyVersion: 2.4
  Include:
    # Include important files that don't end in .rb
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
    - 'Gemfile'
  Exclude:
    # exclude files in /vendor because some CI systems put gems in here e.g.
    # TravisCI
    - 'vendor/**/*'
    # exclude the autogenerated schema file as we don't have any control over
    # its format
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'doc/**/*'
    - 'db/migrate/**/*'

Naming/FileName:
  Exclude:
    - Gemfile
    - Gemfile.lock
