sudo: required
language: ruby
cache:
  bundler: true
  yarn: true
services:
  - postgresql

# Note: we will build pull requests, and these branches
# This stops travis running two jobs on every pull requests
branches:
  only:
  - master
  - dev

before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- export PATH=$PWD/geckodriver:$PATH

before_script:
- yarn install
- ./scripts/install_phantomjs.sh
- RAILS_ENV=test bundle exec rake db:create db:migrate
- RAILS_ENV=test bundle exec rake assets:precompile
- export PERCY_TARGET_BRANCH=$TRAVIS_BRANCH
- export PERCY_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH

script:
- npx percy exec -- bundle exec rspec

after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t simplecov --id $CC_TEST_REPORTER_ID"

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: lczUIdll3TOtzo7K1YRAL0xewC2SzL5QD3Bh1knAsBy4N2n8UyLhcIKimbTrOoMpT9hjUP1ZG/VikzqRo0leRFgrMs11sKy2KpwvRmQf6GcTM8BvOU9LZSxxEyyCYj3n6+6SuYS2Uz4NuSKbNcMazk5E7WAFi5quWAINIFoQuNx0IG2Z3t3GKsiYX6aYoQ643E9x31dhi8zMTCfrCug4IWQTrXr/d18p5KjH4v5BYHnmJSQeNUF+Mhf1bKASNzIHfrxj+akrq9wpz8e4uM50FKeKGYfOyTDULHpwKH9R4rKSWm3J2HHnn+DsSTBJ/lMGud09bvEpMuI6iZpnnRmVGAQBAdk6gdynITDVKtP463yhDSmUTOb9GHptr3zTbABs2PmT6P3XxROdFZKTrrHPiLcPGJVULJ9dA62IQySiSbe4T/mHaCe0izDyxAzdXBQ0Vh659qc2e4gxN6iYktXVLiA8NsCgNuTySxicsEU3AbHR1/AgPfG1PwB4YUqhlauWe7PsDL1o/sUuSVkamxLetghSQICIy1pgygjT0AOZDE2uvZ3jDQubDjTlptFfh4a7ZsXVZsUap5JaaLWBl+3j5orG7rtrYucW/qrc+QEM7yZHfyHfMN69lZTb/kR8jIQ2V+cSYLkjsCcDIQcQ9vDTcZD+5oiuRTXWBCPq4zN/eCA=
  on:
    repo: ServiceInnovationLab/RapuTure
  app:
    dev: rulestestnz
    master: raputure

  run:
  - bundle install
  - yarn install
  - bundle exec rake tmp:cache:clear
  - bundle exec rake db:migrate
  - bundle exec rake assets:precompile
  - restart
env:
  global:
    - RAILS_ENV=test
    - OPENFISCA_URL=https://api.rules.nz
    - GITHUB_URL=https://github.com/ServiceInnovationLab/openfisca-aotearoa
    - OPENFISCA_GIT_CLONE_URL=https://github.com/ServiceInnovationLab/openfisca-aotearoa
    - secure: T7+npfKb6EW0G++OP4C91y2WMrMYyOrozeNT1WPCuedd5vKdILSskMz5LBav54F0J6OBbwozH82e0xclMTa23VuOrc9805tEcwtSRdDYb/mIb7F6gEyseqLIk/TZvDfmB5Yrrji0IVX9s5q0OKfVVb0rTrgh87pSRW2YnYAu41k6v2pK/OquixQX0sogblOLfKYprqh4h3Ay6+1IIDmC/lg0XSe+0xRFBZ5FJk0ycStu74xM+qbphIFgzd6q2kChFqRrOporeCgN3WSAFsQd7QneLITN3eucH9AR0OC9Udpuxr8tvAqTfy7Lo3ogj9PTYjD60ObQjcr212d/isSaZd6Zk2wHH35bzsZU3Y5f6vsILiZVJY2rDPkf7A6jMrWSPw8jd/CRizFjedveF9jCy3J2viwNI23y4Ce+sQkc5u0dAV3Z7n5Avy1R/UjyBpRoYb7VhfX1mZTKsVfLPoOxMuvChyOAL4MZGR83N9emHoLFL1r/JsRlqtun/F8i7vsu3OmqpO9ZcexEh+jx1Hqt6qSizNto6bQkKQ5WOul0kfT9U4kIHcKe0EIsUmD2d6CYLXBIYuSitp3/Fq/yX/tUwm9tJED+J0g76g8ItFAznf+7nYe4MSh039ehOKXLW4v+w6624RYfmjCauNHb4HSmwE0n2y8XgLwat7Tj1hwV8Qc=
